runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

resources:
  cpu: 2
  memory_gb: 4.0
  disk_size_gb: 20

readiness_check:
  path: '/readiness_check'
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 10
  success_threshold: 1
  app_start_timeout_sec: 300

endpoints_api_service:
  name: pythontestapp2.appspot.com
  rollout_strategy: managed